server:
  port: 8081
  tomcat:
    max-connections: 2000
    threads:
      max: 2000
  servlet:
    session:
      timeout: 7200

spring:
  datasource:
    url: jdbc:mysql://62.234.153.162:13306/spring_quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&noAccessToProcedureBodies=true
      #用户名
    username: root
      #密码
    password: root
      #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
      #存入emoji表情符号的配置
    connection-init-sql: SET NAMES utf8mb4;
    max-lifetime: 60000

mybatis:
  mapper-locations: classpath:mappings/**/*.xml
  #typeAliasesPackage:
  config-location: classpath:mybatis-config.xml
  #typeAliasesSuperType:
  #mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


